name: Build and Release for Linux

on:
  release:
    types:
      - created 

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro: [ubuntu, arch]

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          APPIMAGE_TOOL=appimagetool-x86_64.AppImage
          echo "APPIMAGE_TOOL=$APPIMAGE_TOOL" >> GITHUB_ENV

          sudo apt-get update
          sudo apt-get install -y wget

          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/$APPIMAGE_TOOL
          chmod +x $APPIMAGE_TOOL

      - name: Build Docker Image
        run: |
          docker build -f deployment/${{ matrix.distro }}/Dockerfile -t ${{ matrix.distro }}-qlp:latest -o . .

      - name: Run Docker Image
        run: |
          VOLUME=volume

          mkdir $VOLUME
          docker run docker run -v ./$VOLUME:/output ${{ matrix.distro }}-qlp
          cp -r $VOLUME/AppDir .

      - name: Build AppImage
        run: |
          ./$APPIMAGE_TOOL AppDir qlp.AppImage

      - name: Upload AppImage
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./qlp.AppImage
          asset_name: qlp-game-${{ matrix.distro }}.AppImage
          asset_content_type: application/octet-stream
