name: Build and Release for Linux

on:
  release:
    types:
      - created 

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        distro: [ubuntu, arch]

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip wget

      - name: Build with docker
        run: |
          docker build -f deployment/${{ matrix.distro }}/Dockerfile -o . .

      - name: Zip Outputs
        run: |
          zip -r output.zip qlp assets

      - name: Upload Linux Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./output.zip
          asset_name: qlp-game-linux-${{ matrix.distro }}.zip
          asset_content_type: application/octet-stream
